### ISSUE TITLE
Issue with Settings API URL

### ISSUE THREAD

**Issue by bmammon** [cramis1/Marclock-with-CGM-weather#1]
Hello,

First of all, I want to say that I love your watch face!

I use Spike and the Settings API URL is http://127.0.0.1:1979/api/v1/status.json. It would be helpful to other Spike users if you could add this URL to your README.

My high/low thresholds in Spike are as follows:

![screen shot 2018-08-26 at 9 50 34 am](https://user-images.githubusercontent.com/26399567/44630628-82e12280-a915-11e8-8989-9a387b6d3c11.png)

High = 10 mmol/L
Low = 4 mmol/L

But this is what my clock face looks like:

![img_3525](https://user-images.githubusercontent.com/26399567/44630561-5082f580-a914-11e8-8a15-a3a30da8a0bc.JPG)

High threshold of 10 gets imported correctly, but it seems that the watch face is using my Urgent Low threshold instead of the Low threshold.

Ideally I would prefer to enter my high/low threshold manually, without a URL. Even though I have my high threshold set as 10 on Spike, that is just to graphically see when I'm high. I have my actual alerts set higher. The Settings API URL doesn't provide that flexibility.

Thank you again for this great watch face!

**Comment by cramis1** [comment]
Okay thanks for letting me know. I dont own an iphone so I cant test out spike. Are you able to copy and paste the json output from http://127.0.0.1:1979/api/v1/status.json?

I can try to include an option for inserting the high and low manually too.

**Comment by bmammon** [comment]
{"version":"0.10.3-dev-20171205","careportalEnabled":false,"status":"ok","boluscalcEnabled":false,"head":"","settings":{"heartbeat":"10","alarmUrgentLowMins":[5,15,30,45,60,90,120],"timeFormat":12,"scaleY":"log-dynamic","alarmTimeagoUrgent":true,"alarmWarnMins":[30,60,90,120],"nightMode":false,"alarmLowMins":[15,30,45,60,90,120],"alarmHigh":true,"editMode":"on","language":"en","theme":"colors","authDefaultRoles":"readable","showRawbg":"always","alarmTimeagoUrgentMins":"30","DEFAULT_FEATURES":["bgnow","delta","direction","timeago","devicestatus","upbat","errorcodes","profile"],"showPlugins":"careportal iob cob bwp treatmentnotify basal pushover maker sage boluscalc rawbg upbat delta direction upbat rawbg","alarmUrgentLow":true,"alarmLow":true,"alarmTypes":["simple"],"units":"mmol","alarmUrgentHigh":true,"alarmUrgentHighMins":[30,45,60,90,120],"alarmHighMins":[30,45,60,90,120],"thresholds":{"bgTargetTop":290,"bgLow":58,"bgTargetBottom":72,"bgHigh":180},"enable":["careportal","iob","cob","bwp","treatmentnotify","basal","pushover","maker","sage","boluscalc","rawbg","upbat","pushover","treatmentnotify","bgnow","delta","direction","timeago","devicestatus","errorcodes","profile","simplealarms"],"alarmUrgentMins":[30,60,90,120],"focusHours":3,"baseURL":"http://127.0.0.1:1979","alarmTimeagoWarn":true,"showForecast":"ar2","customTitle":"Spike","alarmTimeagoWarnMins":15},"serverTime":"2018-08-27T00:26:14.000+0000","name":"Nightscout","extendedSettings":{"basal":{"render":"default"},"sage":{"warn":504,"info":336,"enableAlerts":true},"errorcodes":{"urgent":"9 10","warn":"1 2 3 4 5 6 7 8","info":"1 2 3 4 5 6 7 8"},"timeago":{"enableAlerts":true}},"serverTimeEpoch":1535329574632,"authorized":null,"apiEnabled":true}

**Comment by bmammon** [comment]
'''{"version":"0.10.3-dev-20171205","careportalEnabled":false,"status":"ok","boluscalcEnabled":false,"head":"","settings":{"heartbeat":"10","alarmUrgentLowMins":[5,15,30,45,60,90,120],"timeFormat":12,"scaleY":"log-dynamic","alarmTimeagoUrgent":true,"alarmWarnMins":[30,60,90,120],"nightMode":false,"alarmLowMins":[15,30,45,60,90,120],"alarmHigh":true,"editMode":"on","language":"en","theme":"colors","authDefaultRoles":"readable","showRawbg":"always","alarmTimeagoUrgentMins":"30","DEFAULT_FEATURES":["bgnow","delta","direction","timeago","devicestatus","upbat","errorcodes","profile"],"showPlugins":"careportal iob cob bwp treatmentnotify basal pushover maker sage boluscalc rawbg upbat delta direction upbat rawbg","alarmUrgentLow":true,"alarmLow":true,"alarmTypes":["simple"],"units":"mmol","alarmUrgentHigh":true,"alarmUrgentHighMins":[30,45,60,90,120],"alarmHighMins":[30,45,60,90,120],"thresholds":{"bgTargetTop":290,"bgLow":58,"bgTargetBottom":72,"bgHigh":180},"enable":["careportal","iob","cob","bwp","treatmentnotify","basal","pushover","maker","sage","boluscalc","rawbg","upbat","pushover","treatmentnotify","bgnow","delta","direction","timeago","devicestatus","errorcodes","profile","simplealarms"],"alarmUrgentMins":[30,60,90,120],"focusHours":3,"baseURL":"http://127.0.0.1:1979","alarmTimeagoWarn":true,"showForecast":"ar2","customTitle":"Spike","alarmTimeagoWarnMins":15},"serverTime":"2018-08-27T00:26:14.000+0000","name":"Nightscout","extendedSettings":{"basal":{"render":"default"},"sage":{"warn":504,"info":336,"enableAlerts":true},"errorcodes":{"urgent":"9 10","warn":"1 2 3 4 5 6 7 8","info":"1 2 3 4 5 6 7 8"},"timeago":{"enableAlerts":true}},"serverTimeEpoch":1535329574632,"authorized":null,"apiEnabled":true}'''

**Comment by bmammon** [comment]
`{"version":"0.10.3-dev-20171205","careportalEnabled":false,"status":"ok","boluscalcEnabled":false,"head":"","settings":{"heartbeat":"10","alarmUrgentLowMins":[5,15,30,45,60,90,120],"timeFormat":12,"scaleY":"log-dynamic","alarmTimeagoUrgent":true,"alarmWarnMins":[30,60,90,120],"nightMode":false,"alarmLowMins":[15,30,45,60,90,120],"alarmHigh":true,"editMode":"on","language":"en","theme":"colors","authDefaultRoles":"readable","showRawbg":"always","alarmTimeagoUrgentMins":"30","DEFAULT_FEATURES":["bgnow","delta","direction","timeago","devicestatus","upbat","errorcodes","profile"],"showPlugins":"careportal iob cob bwp treatmentnotify basal pushover maker sage boluscalc rawbg upbat delta direction upbat rawbg","alarmUrgentLow":true,"alarmLow":true,"alarmTypes":["simple"],"units":"mmol","alarmUrgentHigh":true,"alarmUrgentHighMins":[30,45,60,90,120],"alarmHighMins":[30,45,60,90,120],"thresholds":{"bgTargetTop":290,"bgLow":58,"bgTargetBottom":72,"bgHigh":180},"enable":["careportal","iob","cob","bwp","treatmentnotify","basal","pushover","maker","sage","boluscalc","rawbg","upbat","pushover","treatmentnotify","bgnow","delta","direction","timeago","devicestatus","errorcodes","profile","simplealarms"],"alarmUrgentMins":[30,60,90,120],"focusHours":3,"baseURL":"http://127.0.0.1:1979","alarmTimeagoWarn":true,"showForecast":"ar2","customTitle":"Spike","alarmTimeagoWarnMins":15},"serverTime":"2018-08-27T00:26:14.000+0000","name":"Nightscout","extendedSettings":{"basal":{"render":"default"},"sage":{"warn":504,"info":336,"enableAlerts":true},"errorcodes":{"urgent":"9 10","warn":"1 2 3 4 5 6 7 8","info":"1 2 3 4 5 6 7 8"},"timeago":{"enableAlerts":true}},"serverTimeEpoch":1535329574632,"authorized":null,"apiEnabled":true}`

**Comment by cramis1** [comment]
Thanks.

Manual input of settings is availble in the latest revision on the git now. Should be part of published gallery clock face once fitbit reviews it.

**Comment by bmammon** [comment]
Love the update! Thank you so much, this watch face is perfect!!
