### ISSUE TITLE
Date field too short (Versa 2)

### ISSUE THREAD

**Issue by jbuckhi** [cramis1/Marclock-with-CGM-weather#17]
Hi,
I have a "Versa 2". The language setting of my Fitbit account is "Germany".
Today we have "**Oct. 12**", but the date of my Versa 2 shows up as "**Oct. 1**". So the "2" at the end is missing. Is there a workaround, or is it a display problem on the Versa 2?

**Comment by cramis1** [comment]
Try updating the app, an update was just pushed to fix the issue.
