### ISSUE TITLE
Feature Request: IOB/COB, Snooze Spike Alarms

### ISSUE THREAD

**Issue by bmammon** [cramis1/Marclock-with-CGM-weather#2]
If there's any way to add it, it would be great to see carbs on board and insulin on board on the watchface. Like this: https://github.com/stackenblochen/SimpleGlance

It would also be great to be able to snooze Spike's alarms. Miguel has added it to the status.json endpoint and it will be available in the next update

![screen shot 2018-08-26 at 9 56 05 am](https://user-images.githubusercontent.com/26399567/44630711-e7e94800-a916-11e8-9b39-9055712872ec.png)

**Comment by cramis1** [comment]
Cool. I can look to include insulin on board data. There is not too much screen real estate left so I will have to squeeze it in somewhere.

For the second point, you can already choose to disable alerts from the settings menu, which hopefully should do tge same thing.

**Comment by cramis1** [comment]
IOB/COB is included in the latest revision on the git now. Should be part of gallery clock face once fitbit reviews it.

**Comment by miguelkennedy** [comment]
To add a bit to this discussion...

You can also snooze all Spike alarms for a period of time in minutes just by calling this URL

http://127.0.0.1:1979/spikesnooze?snoozeTime=NUMBER_OF_MINUTES_TO_SNOOZE, for instance http://127.0.0.1:1979/spikesnooze?snoozeTime=30 (snoozes all alarms for 30 minutes)

Or unsnooze all previously snoozed alarms by calling this URL http://127.0.0.1:1979/spikeunsnooze

Here's also an example output of the endpoint @bmammon was referring to (only available in the next Spike update). Hope this helps.

![snoozed](https://user-images.githubusercontent.com/17232641/44808783-07a59800-abc5-11e8-803d-58c74dfb77ee.png)

**Comment by cramis1** [comment]
Hi Miguel,

Thanks for that explanation. That's a really cool functionality! 

Unfortunately I don't have an iPhone so I can't really test this functionality to implement it for this clock face. Do you know if xdrip+ developers are planning to update their status.json similarly?

**Comment by miguelkennedy** [comment]
I really don't know... I added this feature to the internal HTTP server due to a developer request... Maybe JamOrHam will implement it as well if you ask in the Gitter channel... It was fairly easy to implement in Spike...

**Comment by cramis1** [comment]
Apparently you can in xdrip using "http://127.0.0.1:17580/sgv.json?tasker=osnooze".

Alright in the newest update, hitting snooze on the alert should snooze the alert on xdrip+ and spike.

Let me know if it is not working on spike as I can't test it.

**Comment by miguelkennedy** [comment]
Sounds good! ;)

**Comment by bmammon** [comment]
AMAZING! Wow, this is so incredible.  I love the tiny IOB and COB! I'll let you know if snoozing works once the next Spike update is released :D 

Thank you both so much

**Comment by francesc0-cgm** [comment]
Could predicted bg and t basal included too for loop users?

**Comment by cramis1** [comment]
Is that data outputted by Xdrip+? Can you post an example API output? I dont use that feature so I dont know

**Comment by francesc0-cgm** [comment]
No from api/v1/treatment.json on NS site

**Comment by cramis1** [comment]
Oh ok. That will require another API call. I can look to implement it but it will take a bit

**Comment by francesc0-cgm** [comment]
Thank you so much. Glad to test it if and when it will be ready

**Comment by sethgagnon** [comment]
Is IOB and COB available on the fitbit watchface too? Great work here!

**Comment by bmammon** [comment]
Yes, it is!

**Comment by sethgagnon** [comment]
Awesome, I don't see it yet, but maybe it is still working its way through Fitbit approval

**Comment by cramis1** [comment]
Hmm you dont see the IOB and COB? it should be on there on the bottom left of the screen.

If you dont see it, its likely that Xdrip or Spike arent sending that info out. Try typing the Data API URL into your browser and see if it states the IOB and COB values.

**Comment by sethgagnon** [comment]
I do see some entries for IOB. Does the screenshot of the data api look right?
![screenshot_20180910-115205](https://user-images.githubusercontent.com/597958/45308714-2292d900-b4f0-11e8-92e6-c352b0dff1f6.png)

**Comment by cramis1** [comment]
Hmmm there's no IOB or COB in that API data feed.

Is your xdrip version updated?

**Comment by sethgagnon** [comment]
Yep, using latest nightly. I am also having Aaps share the IOB and cob data via local broadcast to xdrip

**Comment by cramis1** [comment]
So is the 0.36U to insulin on board then? and the 0g the COB?

**Comment by sethgagnon** [comment]
Yes

**Comment by cramis1** [comment]
ok. Ill have to look into implementing that. Because they put it all into one string it makes it a bit more tricky because I have to search through the string to pull out the data we need. Im guessing if I just put the whole aaps string it would be too long and overlap the graph.

**Comment by sethgagnon** [comment]
Ah yeah, bummer. Sorry! Thanks for looking into it.

**Comment by sethgagnon** [comment]
The 1.50 is the temp basal rate, the 0.36 is the IOB and the 0 is COB.

**Comment by cramis1** [comment]
@sethgagnon Do you know how to load a watch face via the developer menu? Want to test out the latest update I just uploaded on this git to see if it works? I cant really test it

**Comment by sethgagnon** [comment]
@cramis1 havent done it in a while. i think i still have developer studio installed. if not, ill check it out. thanks!!

**Comment by cramis1** [comment]
@sethgagnon You can follow these steps https://github.com/Rytiggy/Glance/blob/master/HowToInstall.md to install the clock face through the developer settings. Except use the code from this github

**Comment by sethgagnon** [comment]
I keep getting Sideload Failed. Doesnt give me any other errors. The build worked successfully

**Comment by cramis1** [comment]
Change your clock face to some regular clock face. Then try again. Sometimes that happens because Marclock is a large file so when you sideload it, its just too big to have twice. (I think anyway)

**Comment by sethgagnon** [comment]
I got it loaded, but not getting any data to show. I let it go for 10 min to see if it just needed to wait for new readings, but no go.
![testmarclock-screenshot 1](https://user-images.githubusercontent.com/597958/45321456-6d721800-b513-11e8-96e9-49f0f60139a9.png)

**Comment by cramis1** [comment]
in the fitbit studio, in the "console", does it says cant get a connection with companion? If so, maybe try running it once or twice again...

**Comment by sethgagnon** [comment]
yea, thats exactly what i keep getting. i have ran it 3 times, but still getting the same error i shared above about the no connection.

**Comment by cramis1** [comment]
Hmm. In the console, can you find the line that starts with "Matches:" and post what it says?

**Comment by sethgagnon** [comment]
https://gist.github.com/sethgagnon/44b647954e3c1b869078a62ab35e040d

**Comment by cramis1** [comment]
k Ill have to play around with it more. Sorry

**Comment by sethgagnon** [comment]
no prob, i appreciate you checking this for me!

**Comment by cramis1** [comment]
@sethgagnon Okay I updated it, let me know if the github version works now.

**Comment by sethgagnon** [comment]
@cramis1 got an error after it sideloaded:

![image](https://user-images.githubusercontent.com/597958/45430123-a83e9200-b672-11e8-8dab-6029652bd417.png)

![testmarclock-screenshot](https://user-images.githubusercontent.com/597958/45430161-bf7d7f80-b672-11e8-8b89-0ac78b832038.png)

**Comment by sethgagnon** [comment]
@cramis1 let me know if you need any other info that could help

**Comment by cramis1** [comment]
@sethgagnon Sorry I havent had the opportunity to play around with it some more. Hopefully will do so this weekend.

**Comment by cramis1** [comment]
@sethgagnon Ok can you test the latest version uploaded to this git? Im hoping this one should work

**Comment by sethgagnon** [comment]
![testmarclock-screenshot](https://user-images.githubusercontent.com/597958/45570933-9572bb80-b832-11e8-9ba6-bfd81e311932.png)

Looks like it works!! Nice work! Font is kind of small, but i know there is only so much real estate on the screen. Thanks!

**Comment by cramis1** [comment]
Okay great!
uh oh though, the trend arrow is missing from your screen. Is that happening a lot?

**Comment by sethgagnon** [comment]
I see the trend error right now, maybe there was a delay after I side loaded

**Comment by cramis1** [comment]
Actually I would try sideloading the repository version I just uploaded. I have a feeling that when the iob/cob gets too long it might go over top of the arrow causing it to disappear. I dont know. But the latest update may fix that. Anyways, hope it works well

**Comment by sethgagnon** [comment]
Thanks again! I just side loaded the latest. I will let you know how it goes.

**Comment by sethgagnon** [comment]
nevermind, shes working now :)
