### ISSUE TITLE
No data with Spike version 2.5.2

### ISSUE THREAD

**Issue by bmammon** [cramis1/Marclock-with-CGM-weather#5]
I reinstalled version 2.5.1 and the watchface is working again. With the newest update (2.5.2), there is no data.

**Comment by cramis1** [comment]
oh thats weird. I dont have an iphone to test it. If you are alright with it, can you paste the Data API URL into safari, with 2.5.2, and paste here what comes up on the browser?

**Comment by bmammon** [comment]
[{"dateString":"2018-09-20T15:21:13.000+0000","units_hint":"mmol","date":1537456873186,"delta":-3,"direction":"Flat","noise":1,"sysTime":"2018-09-20T15:21:13.000+0000","sgv":89}]

**Comment by bmammon** [comment]
Nvm it's working now! Must have been something else.
