### ISSUE TITLE
NaN appearing above glucose reading

### ISSUE THREAD

**Issue by asteele83** [cramis1/Marclock-with-CGM-weather#6]
Hi currently using iPhone and spike with Miao Miao and getting NaN above the blood glucose reading, any advice on how to fix this issue?
Great clockface thank you!

**Comment by asteele83** [comment]
Ooh just downloaded latest version and no blood sugar showing at all just question marks????
Big thank you for the speedy response

**Comment by cramis1** [comment]
Make sure that the watch is able to sync with the fitbit app. Try swiping up to get to the daily activity then swipe down to restart the watch face. See if those things help

**Comment by asteele83** [comment]
Tried that everything but spike info showing??

**Comment by cramis1** [comment]
hmm, can you paste the data API URL into safari and then paste here what it shows?

**Comment by asteele83** [comment]
I restarted the watch and that seems to have done the work now all working beautifully including the delta. 
Thank you so much for your help definitely my favourite face!

**Comment by cramis1** [comment]
ok great!
